name       : qtkeychain
version    : 0.5.0
release    : 1
source     :
    - https://github.com/frankosterfeld/qtkeychain/archive/v0.5.0.tar.gz : e62d7ae9c8ae04784d8a5d0f213aaa22f1c02427e800ce88739e997f499bb514
license    : BSD 3-Clause License
summary    : QtKeychain is a Qt API to store passwords and other secret data securely
description: |
    QtKeychain is a Qt API to store passwords and other secret data securely
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(icu-i18n)
libsplit: no
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
