name       : qtkeychain
version    : 0.13.2
release    : 6
source     :
    - https://github.com/frankosterfeld/qtkeychain/archive/refs/tags/v0.13.2.tar.gz : 20beeb32de7c4eb0af9039b21e18370faf847ac8697ab3045906076afbc4caa5
license    : BSD-3-Clause
component  : security.library
summary    : QtKeychain is a Qt API to store passwords and other secret data securely
description: |
    QtKeychain is a Qt API to store passwords and other secret data securely
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libsecret-1)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
