name       : qtkeychain
version    : 0.10.0
release    : 4
source     :
    - https://github.com/frankosterfeld/qtkeychain/archive/v0.10.0.tar.gz : 5f916cd97843de550467db32d2e10f218b904af5b21cfdfcc7c6425d7dfc3ec2
license    : BSD-3-Clause
component  : security.library
summary    : QtKeychain is a Qt API to store passwords and other secret data securely
description: |
    QtKeychain is a Qt API to store passwords and other secret data securely
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
