name       : qtkeychain
version    : 0.7.0
release    : 3
source     :
    - https://github.com/frankosterfeld/qtkeychain/archive/v0.7.0.tar.gz : 9f9afaae8e909391d7fc932bac95e38befaac5b2eb49f6623a8efec60a2e6a3a
license    : BSD-3-Clause
component  : security.library
summary    : QtKeychain is a Qt API to store passwords and other secret data securely
description: |
    QtKeychain is a Qt API to store passwords and other secret data securely
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
