name       : qtkeychain
version    : 0.13.0
release    : 5
source     :
    - https://github.com/frankosterfeld/qtkeychain/archive/refs/tags/v0.13.0.tar.gz : 5c04ad1c2f1142197544ddbce249c73b45c724bd683e6dc89bdefbc8e6be36e7
license    : BSD-3-Clause
component  : security.library
summary    : QtKeychain is a Qt API to store passwords and other secret data securely
description: |
    QtKeychain is a Qt API to store passwords and other secret data securely
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libsecret-1)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
